// Generated by view binder compiler. Do not edit!
package com.example.biataplon.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.drawerlayout.widget.DrawerLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.biataplon.R;
import com.google.android.material.navigation.NavigationView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMain1Binding implements ViewBinding {
  @NonNull
  private final DrawerLayout rootView;

  @NonNull
  public final AppBarMain1Binding appBarMain1;

  @NonNull
  public final DrawerLayout drawerLayout;

  @NonNull
  public final FrameLayout homeContrainer;

  @NonNull
  public final Toolbar homeToolbar;

  @NonNull
  public final NavigationView navView;

  private ActivityMain1Binding(@NonNull DrawerLayout rootView,
      @NonNull AppBarMain1Binding appBarMain1, @NonNull DrawerLayout drawerLayout,
      @NonNull FrameLayout homeContrainer, @NonNull Toolbar homeToolbar,
      @NonNull NavigationView navView) {
    this.rootView = rootView;
    this.appBarMain1 = appBarMain1;
    this.drawerLayout = drawerLayout;
    this.homeContrainer = homeContrainer;
    this.homeToolbar = homeToolbar;
    this.navView = navView;
  }

  @Override
  @NonNull
  public DrawerLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMain1Binding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMain1Binding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main1, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMain1Binding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.app_bar_main1;
      View appBarMain1 = ViewBindings.findChildViewById(rootView, id);
      if (appBarMain1 == null) {
        break missingId;
      }
      AppBarMain1Binding binding_appBarMain1 = AppBarMain1Binding.bind(appBarMain1);

      DrawerLayout drawerLayout = (DrawerLayout) rootView;

      id = R.id.home_contrainer;
      FrameLayout homeContrainer = ViewBindings.findChildViewById(rootView, id);
      if (homeContrainer == null) {
        break missingId;
      }

      id = R.id.home_toolbar;
      Toolbar homeToolbar = ViewBindings.findChildViewById(rootView, id);
      if (homeToolbar == null) {
        break missingId;
      }

      id = R.id.nav_view;
      NavigationView navView = ViewBindings.findChildViewById(rootView, id);
      if (navView == null) {
        break missingId;
      }

      return new ActivityMain1Binding((DrawerLayout) rootView, binding_appBarMain1, drawerLayout,
          homeContrainer, homeToolbar, navView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
