// Generated by view binder compiler. Do not edit!
package com.example.biataplon.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.biataplon.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityCartBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button buyNow;

  @NonNull
  public final RecyclerView cartRec;

  @NonNull
  public final Toolbar myCartToolbar;

  @NonNull
  public final TextView textView3;

  private ActivityCartBinding(@NonNull ConstraintLayout rootView, @NonNull Button buyNow,
      @NonNull RecyclerView cartRec, @NonNull Toolbar myCartToolbar, @NonNull TextView textView3) {
    this.rootView = rootView;
    this.buyNow = buyNow;
    this.cartRec = cartRec;
    this.myCartToolbar = myCartToolbar;
    this.textView3 = textView3;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityCartBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityCartBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_cart, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityCartBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buy_now;
      Button buyNow = ViewBindings.findChildViewById(rootView, id);
      if (buyNow == null) {
        break missingId;
      }

      id = R.id.cart_rec;
      RecyclerView cartRec = ViewBindings.findChildViewById(rootView, id);
      if (cartRec == null) {
        break missingId;
      }

      id = R.id.my_cart_toolbar;
      Toolbar myCartToolbar = ViewBindings.findChildViewById(rootView, id);
      if (myCartToolbar == null) {
        break missingId;
      }

      id = R.id.textView3;
      TextView textView3 = ViewBindings.findChildViewById(rootView, id);
      if (textView3 == null) {
        break missingId;
      }

      return new ActivityCartBinding((ConstraintLayout) rootView, buyNow, cartRec, myCartToolbar,
          textView3);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
