// Generated by view binder compiler. Do not edit!
package com.example.biataplon.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.biataplon.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityAddressBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button addAddressBtn;

  @NonNull
  public final RecyclerView addressRecycler;

  @NonNull
  public final Toolbar addressToolbar;

  @NonNull
  public final Button paymentBtn;

  private ActivityAddressBinding(@NonNull ConstraintLayout rootView, @NonNull Button addAddressBtn,
      @NonNull RecyclerView addressRecycler, @NonNull Toolbar addressToolbar,
      @NonNull Button paymentBtn) {
    this.rootView = rootView;
    this.addAddressBtn = addAddressBtn;
    this.addressRecycler = addressRecycler;
    this.addressToolbar = addressToolbar;
    this.paymentBtn = paymentBtn;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAddressBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAddressBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_address, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAddressBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.add_address_btn;
      Button addAddressBtn = ViewBindings.findChildViewById(rootView, id);
      if (addAddressBtn == null) {
        break missingId;
      }

      id = R.id.address_recycler;
      RecyclerView addressRecycler = ViewBindings.findChildViewById(rootView, id);
      if (addressRecycler == null) {
        break missingId;
      }

      id = R.id.address_toolbar;
      Toolbar addressToolbar = ViewBindings.findChildViewById(rootView, id);
      if (addressToolbar == null) {
        break missingId;
      }

      id = R.id.payment_btn;
      Button paymentBtn = ViewBindings.findChildViewById(rootView, id);
      if (paymentBtn == null) {
        break missingId;
      }

      return new ActivityAddressBinding((ConstraintLayout) rootView, addAddressBtn, addressRecycler,
          addressToolbar, paymentBtn);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
