// Generated by view binder compiler. Do not edit!
package com.example.biataplon.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.RadioButton;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.biataplon.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class AddressItemBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView addressAdd;

  @NonNull
  public final RadioButton selectAddress;

  private AddressItemBinding(@NonNull ConstraintLayout rootView, @NonNull TextView addressAdd,
      @NonNull RadioButton selectAddress) {
    this.rootView = rootView;
    this.addressAdd = addressAdd;
    this.selectAddress = selectAddress;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static AddressItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AddressItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.address_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AddressItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.address_add;
      TextView addressAdd = ViewBindings.findChildViewById(rootView, id);
      if (addressAdd == null) {
        break missingId;
      }

      id = R.id.select_address;
      RadioButton selectAddress = ViewBindings.findChildViewById(rootView, id);
      if (selectAddress == null) {
        break missingId;
      }

      return new AddressItemBinding((ConstraintLayout) rootView, addressAdd, selectAddress);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
