// Generated by view binder compiler. Do not edit!
package com.example.biataplon.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.biataplon.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class MyCartItemBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final TextView currentDate;

  @NonNull
  public final TextView currentTime;

  @NonNull
  public final TextView productName;

  @NonNull
  public final TextView productPrice;

  @NonNull
  public final TextView totalPrice;

  @NonNull
  public final TextView totalQuantity;

  private MyCartItemBinding(@NonNull CardView rootView, @NonNull TextView currentDate,
      @NonNull TextView currentTime, @NonNull TextView productName, @NonNull TextView productPrice,
      @NonNull TextView totalPrice, @NonNull TextView totalQuantity) {
    this.rootView = rootView;
    this.currentDate = currentDate;
    this.currentTime = currentTime;
    this.productName = productName;
    this.productPrice = productPrice;
    this.totalPrice = totalPrice;
    this.totalQuantity = totalQuantity;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static MyCartItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static MyCartItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.my_cart_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static MyCartItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.current_date;
      TextView currentDate = ViewBindings.findChildViewById(rootView, id);
      if (currentDate == null) {
        break missingId;
      }

      id = R.id.current_time;
      TextView currentTime = ViewBindings.findChildViewById(rootView, id);
      if (currentTime == null) {
        break missingId;
      }

      id = R.id.product_name;
      TextView productName = ViewBindings.findChildViewById(rootView, id);
      if (productName == null) {
        break missingId;
      }

      id = R.id.product_price;
      TextView productPrice = ViewBindings.findChildViewById(rootView, id);
      if (productPrice == null) {
        break missingId;
      }

      id = R.id.total_price;
      TextView totalPrice = ViewBindings.findChildViewById(rootView, id);
      if (totalPrice == null) {
        break missingId;
      }

      id = R.id.total_quantity;
      TextView totalQuantity = ViewBindings.findChildViewById(rootView, id);
      if (totalQuantity == null) {
        break missingId;
      }

      return new MyCartItemBinding((CardView) rootView, currentDate, currentTime, productName,
          productPrice, totalPrice, totalQuantity);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
