// Generated by view binder compiler. Do not edit!
package com.example.biataplon.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.biataplon.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class PopularItemsBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final ImageView allImg;

  @NonNull
  public final TextView allPrice;

  @NonNull
  public final TextView allProductName;

  @NonNull
  public final TextView dollar;

  private PopularItemsBinding(@NonNull CardView rootView, @NonNull ImageView allImg,
      @NonNull TextView allPrice, @NonNull TextView allProductName, @NonNull TextView dollar) {
    this.rootView = rootView;
    this.allImg = allImg;
    this.allPrice = allPrice;
    this.allProductName = allProductName;
    this.dollar = dollar;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static PopularItemsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static PopularItemsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.popular_items, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static PopularItemsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.all_img;
      ImageView allImg = ViewBindings.findChildViewById(rootView, id);
      if (allImg == null) {
        break missingId;
      }

      id = R.id.all_price;
      TextView allPrice = ViewBindings.findChildViewById(rootView, id);
      if (allPrice == null) {
        break missingId;
      }

      id = R.id.all_product_name;
      TextView allProductName = ViewBindings.findChildViewById(rootView, id);
      if (allProductName == null) {
        break missingId;
      }

      id = R.id.dollar;
      TextView dollar = ViewBindings.findChildViewById(rootView, id);
      if (dollar == null) {
        break missingId;
      }

      return new PopularItemsBinding((CardView) rootView, allImg, allPrice, allProductName, dollar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
