// Generated by view binder compiler. Do not edit!
package com.example.biataplon.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.biataplon.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ShowAllItemBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView itemCost;

  @NonNull
  public final ImageView itemImage;

  @NonNull
  public final TextView itemNam;

  private ShowAllItemBinding(@NonNull LinearLayout rootView, @NonNull TextView itemCost,
      @NonNull ImageView itemImage, @NonNull TextView itemNam) {
    this.rootView = rootView;
    this.itemCost = itemCost;
    this.itemImage = itemImage;
    this.itemNam = itemNam;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ShowAllItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ShowAllItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.show_all_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ShowAllItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.item_cost;
      TextView itemCost = ViewBindings.findChildViewById(rootView, id);
      if (itemCost == null) {
        break missingId;
      }

      id = R.id.item_image;
      ImageView itemImage = ViewBindings.findChildViewById(rootView, id);
      if (itemImage == null) {
        break missingId;
      }

      id = R.id.item_nam;
      TextView itemNam = ViewBindings.findChildViewById(rootView, id);
      if (itemNam == null) {
        break missingId;
      }

      return new ShowAllItemBinding((LinearLayout) rootView, itemCost, itemImage, itemNam);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
